# syntax=docker/dockerfile:1
FROM python:3.13-slim@sha256:ffb752e139c0a19692a43af8d8523b274222dd68eebad5d583b45c2201c6e30a

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /ingress
COPY scripts/ingress_proxy.py ./ingress_proxy.py
USER 10004:10004
ENTRYPOINT ["python", "/ingress/ingress_proxy.py"]
